/**
 * phoneMirrorConnector-aso.js — Auto-generated ASO wrapper for phoneMirrorConnector.
 * Generated by tools/generate-connector-wrappers.js
 */

const original = require("./phoneMirrorConnector");
const { withAso } = require("../aso-connector-middleware");

// --- Wrap operational functions with ASO telemetry ---
const wrapped_getPhoneMirrorStatus = withAso("phoneMirror", original.getPhoneMirrorStatus);
const wrapped_capturePhoneMirrorSnapshot = withAso("phoneMirror", original.capturePhoneMirrorSnapshot);
const wrapped_sendPhoneTap = withAso("phoneMirror", original.sendPhoneTap);
const wrapped_sendPhoneSwipe = withAso("phoneMirror", original.sendPhoneSwipe);
const wrapped_sendPhoneText = withAso("phoneMirror", original.sendPhoneText);
const wrapped_sendPhoneKey = withAso("phoneMirror", original.sendPhoneKey);
const wrapped_listInstalledWhatsAppTargets = withAso("phoneMirror", original.listInstalledWhatsAppTargets);
const wrapped_openPhoneWhatsApp = withAso("phoneMirror", original.openPhoneWhatsApp);
const wrapped_openPhoneWhatsAppChat = withAso("phoneMirror", original.openPhoneWhatsAppChat);
const wrapped_sendPhoneWhatsAppLinkedMessage = withAso("phoneMirror", original.sendPhoneWhatsAppLinkedMessage);
const wrapped_setPhoneMirrorVoiceOutput = withAso("phoneMirror", original.setPhoneMirrorVoiceOutput);

// --- Re-export everything, replacing wrapped functions ---
module.exports = {
  ...original,
  getPhoneMirrorStatus: wrapped_getPhoneMirrorStatus,
  capturePhoneMirrorSnapshot: wrapped_capturePhoneMirrorSnapshot,
  sendPhoneTap: wrapped_sendPhoneTap,
  sendPhoneSwipe: wrapped_sendPhoneSwipe,
  sendPhoneText: wrapped_sendPhoneText,
  sendPhoneKey: wrapped_sendPhoneKey,
  listInstalledWhatsAppTargets: wrapped_listInstalledWhatsAppTargets,
  openPhoneWhatsApp: wrapped_openPhoneWhatsApp,
  openPhoneWhatsAppChat: wrapped_openPhoneWhatsAppChat,
  sendPhoneWhatsAppLinkedMessage: wrapped_sendPhoneWhatsAppLinkedMessage,
  setPhoneMirrorVoiceOutput: wrapped_setPhoneMirrorVoiceOutput,
};
