/**
 * phoneProMirrorConnector-aso.js — Auto-generated ASO wrapper for phoneProMirrorConnector.
 * Generated by tools/generate-connector-wrappers.js
 */

const original = require("./phoneProMirrorConnector");
const { withAso } = require("../aso-connector-middleware");

// --- Wrap operational functions with ASO telemetry ---
const wrapped_getPhoneProMirrorStatus = withAso("phoneProMirror", original.getPhoneProMirrorStatus);
const wrapped_startPhoneProMirror = withAso("phoneProMirror", original.startPhoneProMirror);
const wrapped_stopPhoneProMirror = withAso("phoneProMirror", original.stopPhoneProMirror);

// --- Re-export everything, replacing wrapped functions ---
module.exports = {
  ...original,
  getPhoneProMirrorStatus: wrapped_getPhoneProMirrorStatus,
  startPhoneProMirror: wrapped_startPhoneProMirror,
  stopPhoneProMirror: wrapped_stopPhoneProMirror,
};
