/**
 * capturesConnector-aso.js — Auto-generated ASO wrapper for capturesConnector.
 * Generated by tools/generate-connector-wrappers.js
 */

const original = require("./capturesConnector");
const { withAso } = require("../aso-connector-middleware");

module.exports = {
  ...original,
};
