/**
 * desktopDisplayConnector-aso.js — Auto-generated ASO wrapper for desktopDisplayConnector.
 * Generated by tools/generate-connector-wrappers.js
 */

const original = require("./desktopDisplayConnector");
const { withAso } = require("../aso-connector-middleware");

// Wrap operational functions with ASO telemetry.
const wrapped_listDesktopDisplays = withAso("desktopDisplay", original.listDesktopDisplays);

module.exports = {
  ...original,
  listDesktopDisplays: wrapped_listDesktopDisplays,
};
