/**
 * desktopControlConnector-aso.js — Auto-generated ASO wrapper for desktopControlConnector.
 * Generated by tools/generate-connector-wrappers.js
 */

const original = require("./desktopControlConnector");
const { withAso } = require("../aso-connector-middleware");

// Wrap operational functions with ASO telemetry.
const wrapped_invokeDesktopInput = withAso("desktopControl", original.invokeDesktopInput);

module.exports = {
  ...original,
  invokeDesktopInput: wrapped_invokeDesktopInput,
};
