/**
 * desktopCaptureConnector-aso.js — Auto-generated ASO wrapper for desktopCaptureConnector.
 * Generated by tools/generate-connector-wrappers.js
 */

const original = require("./desktopCaptureConnector");
const { withAso } = require("../aso-connector-middleware");

// Wrap operational functions with ASO telemetry.
const wrapped_captureDesktopSnapshot = withAso("desktopCapture", original.captureDesktopSnapshot);
const wrapped_captureDesktopLayoutAndWindow = withAso("desktopCapture", original.captureDesktopLayoutAndWindow);

module.exports = {
  ...original,
  captureDesktopSnapshot: wrapped_captureDesktopSnapshot,
  captureDesktopLayoutAndWindow: wrapped_captureDesktopLayoutAndWindow,
};
