/**
 * localRebuildConnector-aso.js — Auto-generated ASO wrapper for localRebuildConnector.
 * Generated by tools/generate-connector-wrappers.js
 */

const original = require("./localRebuildConnector");
const { withAso } = require("../aso-connector-middleware");

module.exports = {
  ...original,
};
