/**
 * phoneBrowserHistoryConnector-aso.js — Auto-generated ASO wrapper for phoneBrowserHistoryConnector.
 * Generated by tools/generate-connector-wrappers.js
 */

const original = require("./phoneBrowserHistoryConnector");
const { withAso } = require("../aso-connector-middleware");

// Wrap operational functions with ASO telemetry.
const wrapped_runPhoneBrowserHistoryCheck = withAso("phoneBrowserHistory", original.runPhoneBrowserHistoryCheck);

module.exports = {
  ...original,
  runPhoneBrowserHistoryCheck: wrapped_runPhoneBrowserHistoryCheck,
};
