/**
 * screenshotConnector-aso.js — Auto-generated ASO wrapper for screenshotConnector.
 * Generated by tools/generate-connector-wrappers.js
 */

const original = require("./screenshotConnector");
const { withAso } = require("../aso-connector-middleware");

// Wrap operational functions with ASO telemetry.
const wrapped_captureScreenshot = withAso("screenshot", original.captureScreenshot);
const wrapped_runBrowserTask = withAso("screenshot", original.runBrowserTask);
const wrapped_closeScreenshotWorker = withAso("screenshot", original.closeScreenshotWorker);

module.exports = {
  ...original,
  captureScreenshot: wrapped_captureScreenshot,
  runBrowserTask: wrapped_runBrowserTask,
  closeScreenshotWorker: wrapped_closeScreenshotWorker,
};
