/**
 * systemPaths-aso.js — Auto-generated ASO wrapper for systemPaths.
 * Generated by tools/generate-connector-wrappers.js
 */

const original = require("./systemPaths");
const { withAso } = require("../aso-connector-middleware");

// Wrap operational functions with ASO telemetry.
const wrapped_resolveToolPaths = withAso("systemPaths", original.resolveToolPaths);

module.exports = {
  ...original,
  resolveToolPaths: wrapped_resolveToolPaths,
};
