/**
 * uiVisualAuditConnector-aso.js — Auto-generated ASO wrapper for uiVisualAuditConnector.
 * Generated by tools/generate-connector-wrappers.js
 */

const original = require("./uiVisualAuditConnector");
const { withAso } = require("../aso-connector-middleware");

// Wrap operational functions with ASO telemetry.
const wrapped_runUiVisualAudit = withAso("uiVisualAudit", original.runUiVisualAudit);

module.exports = {
  ...original,
  runUiVisualAudit: wrapped_runUiVisualAudit,
};
